-- Executable A/B RLS and webhook RPC checks for a development database.
-- Run the entire file as one batch as a database owner (SQL editor / postgres).
-- This file is not part of GitHub Actions.
--
-- The batch records one row per check, then rolls back so no test users,
-- projects, or deliveries remain. Do not DELETE auth.users or product data.
--
-- Output columns: test_name | passed | detail

begin;

create temporary table isolation_results (
  ord integer generated by default as identity,
  test_name text not null,
  passed boolean not null,
  detail text not null
) on commit drop;

do $isolation$
declare
  user_a uuid := 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1';
  user_b uuid := 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1';
  a_project uuid := '11111111-1111-4111-8111-111111111111';
  a_project_b uuid := '22222222-2222-4222-8222-222222222222';
  a_snapshot uuid := '31111111-1111-4111-8111-111111111111';
  a_snapshot_other uuid := '32222222-2222-4222-8222-222222222222';
  b_project uuid := 'c2222222-2222-4222-8222-222222222221';
  b_repo uuid := 'c2111111-1111-4111-8111-111111111111';
  b_snapshot uuid := 'c3333333-3333-4333-8333-333333333331';
  b_install uuid := 'c4444444-4444-4444-8444-444444444441';
  extra_project uuid;
  extra_repo uuid;
  gh_repo uuid;
  hook_project uuid := 'c7777777-7777-4777-8777-777777777771';
  n int;
  n2 int;
  n_before int;
  snap_before uuid;
  snap_count_before int;
  claim jsonb;
  claim2 jsonb;
  upserted boolean;
  access_n int;
  install_ok boolean;
  jobs_created int;
  jobs_created2 int;
  b_name text;
  results jsonb := '[]'::jsonb;
  sha text := 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
  sha_zero text := '0000000000000000000000000000000000000000';
begin
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claim.role', '', true);
  perform set_config('request.jwt.claims', '', true);
  execute 'reset role';

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    confirmation_token, email_change, email_change_token_new, recovery_token
  ) values
    (
      '00000000-0000-0000-0000-000000000000', user_a, 'authenticated', 'authenticated',
      'buildmirror-rls-a@invalid.local', '!', now(),
      '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(),
      '', '', '', ''
    ),
    (
      '00000000-0000-0000-0000-000000000000', user_b, 'authenticated', 'authenticated',
      'buildmirror-rls-b@invalid.local', '!', now(),
      '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(),
      '', '', '', ''
    );

  perform public.seed_buildmirror_demo(user_a);

  insert into public.repositories (
    id, user_id, provider, provider_id, owner, name, default_branch, head_sha, connection_status
  ) values (
    b_repo, user_b, 'mock', 'mock-repo-b-iso', 'user-b', 'b-repo', 'main', repeat('b', 40), 'connected'
  );

  insert into public.projects (id, user_id, name, status, active_repository_id, analysis_branch)
  values (b_project, user_b, 'B project', 'up_to_date', b_repo, 'main');

  insert into public.project_repositories (project_id, repository_id, role)
  values (b_project, b_repo, 'primary');

  insert into public.analysis_snapshots (
    id, project_id, repository_id, branch, commit_sha,
    analysis_engine_version, constitution_version, status, data_source
  ) values (
    b_snapshot, b_project, b_repo, 'main', repeat('b', 40), 'test', 'test', 'completed', 'mock'
  );

  insert into public.github_install_claims (
    nonce, user_id, github_external_installation_id, return_to, expires_at, consumed_at
  ) values (
    'c5555555-5555-4555-8555-555555555551', user_b, 99002, '/projects', now() + interval '1 hour', now()
  );

  insert into public.github_installations (
    id, user_id, github_external_installation_id, account_login, account_type, account_id,
    repository_selection, permissions, events, installed_at
  ) values (
    b_install, user_b, 99002, 'user-b', 'User', 2, 'selected', '{}'::jsonb, '[]'::jsonb, now()
  );

  execute 'set constraints all immediate';
  execute 'set constraints all deferred';

  insert into public.github_install_claims (
    nonce, user_id, github_external_installation_id, return_to, expires_at, consumed_at
  ) values (
    'c6666666-6666-4666-8666-666666666661', user_a, 88001, '/projects', now() + interval '1 hour', now()
  );

  insert into public.github_installations (
    user_id, github_external_installation_id, account_login, account_type, account_id,
    repository_selection, permissions, events, installed_at
  ) values (
    user_a, 88001, 'user-a', 'User', 1, 'selected', '{}'::jsonb, '[]'::jsonb, now()
  );

  insert into public.repositories (
    id, user_id, provider, provider_id, owner, name, default_branch, connection_status
  ) values (
    'c8888888-8888-4888-8888-888888888881', user_a, 'mock', 'mock-repo-a-extra',
    'demo-user', 'extra-own-repo', 'main', 'disconnected'
  );

  perform set_config('request.jwt.claim.sub', user_a::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  perform set_config(
    'request.jwt.claims',
    json_build_object('sub', user_a, 'role', 'authenticated')::text,
    true
  );
  execute 'set local role authenticated';

  select count(*) into n from public.projects where user_id = user_b;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'a_cannot_select_b_projects',
    'passed', n = 0,
    'detail', format('expected=0 actual=%s', n)
  ));

  begin
    update public.projects set name = 'hijack' where id = b_project;
    get diagnostics n = row_count;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_update_b_projects',
      'passed', n = 0,
      'detail', format('expected=0 actual=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_update_b_projects',
      'passed', true,
      'detail', format('expected=0-or-error actual=error:%s', sqlerrm)
    ));
  end;

  begin
    delete from public.projects where id = b_project;
    get diagnostics n = row_count;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_delete_b_projects',
      'passed', n = 0,
      'detail', format('expected=0 actual=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_delete_b_projects',
      'passed', true,
      'detail', format('expected=0-or-error actual=error:%s', sqlerrm)
    ));
  end;

  select count(*) into n from public.github_installations where user_id = user_b;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'a_cannot_select_b_installations',
    'passed', n = 0,
    'detail', format('expected=0 actual=%s', n)
  ));

  select count(*) into n from public.repositories where user_id = user_b;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'a_cannot_select_b_repositories',
    'passed', n = 0,
    'detail', format('expected=0 actual=%s', n)
  ));

  begin
    insert into public.project_repositories (project_id, repository_id)
    values (a_project, b_repo);
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_link_b_repository',
      'passed', false,
      'detail', 'expected=fail actual=inserted'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_link_b_repository',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    execute 'set constraints all immediate';
    update public.projects
      set last_successful_snapshot_id = b_snapshot
      where id = a_project;
    get diagnostics n = row_count;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_ref_b_snapshot',
      'passed', false,
      'detail', format('expected=fail actual=updated=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_ref_b_snapshot',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;
  execute 'set constraints all deferred';

  begin
    insert into public.scores (
      project_id, snapshot_id,
      correctness_summary, nativeness_summary, ownership_summary
    ) values (
      a_project, a_snapshot_other, 'x', 'y', 'z'
    );
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_score_cannot_ref_other_project_snapshot',
      'passed', false,
      'detail', 'expected=fail actual=inserted'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_score_cannot_ref_other_project_snapshot',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    insert into public.analysis_jobs (
      project_id, snapshot_id, type, stage, progress, status
    ) values (
      a_project, a_snapshot_other, 'full', 'queued', 0, 'queued'
    );
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_job_cannot_ref_other_project_snapshot',
      'passed', false,
      'detail', 'expected=fail actual=inserted'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_job_cannot_ref_other_project_snapshot',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    update public.project_view_state
      set snapshot_id = a_snapshot_other
      where user_id = user_a and project_id = a_project;
    get diagnostics n = row_count;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_view_state_cannot_ref_other_project_snapshot',
      'passed', false,
      'detail', format('expected=fail actual=updated=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_view_state_cannot_ref_other_project_snapshot',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    insert into public.github_webhook_deliveries (
      github_delivery_id, github_event, processing_status
    ) values ('delivery-client', 'ping', 'received');
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_insert_webhook_delivery',
      'passed', false,
      'detail', 'expected=fail actual=inserted'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_insert_webhook_delivery',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    insert into public.analysis_jobs (
      project_id, snapshot_id, type, stage, progress, status, trigger_type, github_delivery_id
    ) values (
      a_project, null, 'incremental', 'queued', 0, 'pending', 'github_push', 'delivery-client'
    );
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_insert_github_push_job',
      'passed', false,
      'detail', 'expected=fail actual=inserted'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_insert_github_push_job',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    extra_project := public.create_project_with_repository(
      'A extra', 'demo-user', 'extra-repo', 'main'
    );
    execute 'set constraints all immediate';
    execute 'set constraints all deferred';
    select count(*) into n
    from public.projects
    where id = extra_project and user_id = user_a;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_can_create_own_project',
      'passed', extra_project is not null and n = 1,
      'detail', format('expected=1 actual=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_can_create_own_project',
      'passed', false,
      'detail', format('expected=1 actual=error:%s', sqlerrm)
    ));
  end;

  begin
    perform public.link_project_repository(
      extra_project,
      'c8888888-8888-4888-8888-888888888881'
    );
    execute 'set constraints all immediate';
    execute 'set constraints all deferred';
    select count(*) into n
    from public.project_repositories
    where project_id = extra_project
      and repository_id = 'c8888888-8888-4888-8888-888888888881'
      and unlinked_at is null;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_can_link_own_repository',
      'passed', n = 1,
      'detail', format('expected=1 actual=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_can_link_own_repository',
      'passed', false,
      'detail', format('expected=1 actual=error:%s', sqlerrm)
    ));
  end;

  begin
    perform public.claim_github_webhook_delivery('auth-blocked', 'ping', null, null, null);
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'authenticated_cannot_exec_claim_rpc',
      'passed', false,
      'detail', 'expected=fail actual=executed'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'authenticated_cannot_exec_claim_rpc',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  begin
    perform public.enqueue_github_push_analysis_jobs(
      'auth-blocked', 88001, 800001, 'refs/heads/main', sha
    );
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'authenticated_cannot_exec_enqueue_rpc',
      'passed', false,
      'detail', 'expected=fail actual=executed'
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'authenticated_cannot_exec_enqueue_rpc',
      'passed', true,
      'detail', format('expected=fail actual=error:%s', sqlerrm)
    ));
  end;

  execute 'reset role';
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claim.role', '', true);
  perform set_config('request.jwt.claims', '', true);

  execute 'set local role service_role';

  claim := public.claim_github_webhook_delivery('bm-iso-d1', 'push', null, 88001, 800001);
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_claim_new',
    'passed', coalesce(claim->>'kind', '') = 'new',
    'detail', format('expected=new actual=%s', coalesce(claim->>'kind', 'null'))
  ));

  perform public.finish_github_webhook_delivery('bm-iso-d1', 'processed', null);
  claim2 := public.claim_github_webhook_delivery('bm-iso-d1', 'push', null, 88001, 800001);
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_claim_duplicate',
    'passed', coalesce(claim2->>'kind', '') = 'duplicate',
    'detail', format('expected=duplicate actual=%s', coalesce(claim2->>'kind', 'null'))
  ));

  upserted := public.upsert_github_webhook_repository(
    88001, 800001, 'user-a', 'push-repo', 'user-a/push-repo',
    'https://example.invalid/user-a/push-repo', 'main', false, false, false, now()
  );
  select count(*) into n
  from public.repositories
  where user_id = user_a and github_repository_id = 800001;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_upsert_repository',
    'passed', upserted is true and n = 1,
    'detail', format('expected=1 actual=%s upserted=%s', n, upserted)
  ));

  install_ok := public.apply_github_webhook_installation(88001, 'suspend', now());
  select count(*) into n
  from public.github_installations
  where github_external_installation_id = 88001 and suspended_at is not null;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_apply_installation_suspend',
    'passed', install_ok is true and n = 1,
    'detail', format('expected=1 actual=%s', n)
  ));

  install_ok := public.apply_github_webhook_installation(88001, 'unsuspend', now());
  select count(*) into n
  from public.github_installations
  where github_external_installation_id = 88001
    and suspended_at is null
    and deleted_at is null;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_apply_installation_unsuspend',
    'passed', install_ok is true and n = 1,
    'detail', format('expected=1 actual=%s', n)
  ));

  access_n := public.apply_github_webhook_repository_access(
    88001, array[800001]::bigint[], false, now()
  );
  select count(*) into n
  from public.repositories
  where github_repository_id = 800001 and connection_status = 'inaccessible';
  access_n := access_n + public.apply_github_webhook_repository_access(
    88001, array[800001]::bigint[], true, now()
  );
  select count(*) into n2
  from public.repositories
  where github_repository_id = 800001 and connection_status = 'connected';
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_apply_repository_access',
    'passed', n = 1 and n2 = 1,
    'detail', format('expected=inaccessible:1 connected:1 actual=inaccessible:%s connected:%s', n, n2)
  ));

  execute 'reset role';
  execute 'set constraints all deferred';

  select id into gh_repo
  from public.repositories
  where user_id = user_a and github_repository_id = 800001;

  insert into public.projects (
    id, user_id, name, status, active_repository_id, analysis_branch
  ) values (
    hook_project, user_a, 'webhook target', 'up_to_date', null, 'main'
  );
  insert into public.project_repositories (project_id, repository_id, role)
  values (hook_project, gh_repo, 'primary');
  update public.projects
    set active_repository_id = gh_repo
    where id = hook_project;
  execute 'set constraints all immediate';
  execute 'set constraints all deferred';

  select last_successful_snapshot_id into snap_before
  from public.projects where id = a_project;
  select count(*) into snap_count_before
  from public.analysis_snapshots where project_id = a_project;
  select count(*) into n_before
  from public.analysis_jobs
  where project_id = hook_project and trigger_type = 'github_push';

  execute 'set local role service_role';

  jobs_created := public.enqueue_github_push_analysis_jobs(
    'bm-iso-d1', 88001, 800001, 'refs/heads/main', sha
  );
  select count(*) into n
  from public.analysis_jobs
  where project_id = hook_project
    and trigger_type = 'github_push'
    and github_delivery_id = 'bm-iso-d1';
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_enqueue_default_branch_job',
    'passed', jobs_created = 1 and n = 1,
    'detail', format('expected=1 actual_created=%s actual_rows=%s', jobs_created, n)
  ));

  jobs_created2 := public.enqueue_github_push_analysis_jobs(
    'bm-iso-d1', 88001, 800001, 'refs/heads/main', sha
  );
  select count(*) into n
  from public.analysis_jobs
  where github_delivery_id = 'bm-iso-d1';
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_enqueue_same_delivery_no_dup',
    'passed', jobs_created2 = 0 and n = 1,
    'detail', format('expected_created=0 expected_rows=1 actual_created=%s actual_rows=%s', jobs_created2, n)
  ));

  perform public.claim_github_webhook_delivery('bm-iso-d2', 'push', null, 88001, 800001);
  jobs_created2 := public.enqueue_github_push_analysis_jobs(
    'bm-iso-d2', 88001, 800001, 'refs/heads/main', sha
  );
  select count(*) into n
  from public.analysis_jobs
  where project_id = hook_project
    and repository_id = gh_repo
    and trigger_sha = sha
    and trigger_type = 'github_push';
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_enqueue_same_sha_no_dup',
    'passed', jobs_created2 = 0 and n = 1,
    'detail', format('expected_created=0 expected_rows=1 actual_created=%s actual_rows=%s', jobs_created2, n)
  ));

  jobs_created2 := public.enqueue_github_push_analysis_jobs(
    'bm-iso-d3', 88001, 800001, 'refs/heads/develop', sha
  );
  select count(*) into n
  from public.analysis_jobs
  where github_delivery_id = 'bm-iso-d3';
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_enqueue_other_branch_no_job',
    'passed', jobs_created2 = 0 and n = 0,
    'detail', format('expected=0 actual_created=%s actual_rows=%s', jobs_created2, n)
  ));

  jobs_created2 := public.enqueue_github_push_analysis_jobs(
    'bm-iso-d4', 88001, 800001, 'refs/heads/main', sha_zero
  );
  select count(*) into n
  from public.analysis_jobs
  where github_delivery_id = 'bm-iso-d4';
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_enqueue_delete_push_no_job',
    'passed', jobs_created2 = 0 and n = 0,
    'detail', format('expected=0 actual_created=%s actual_rows=%s', jobs_created2, n)
  ));

  execute 'reset role';

  select count(*) into n
  from public.analysis_snapshots where project_id = a_project;
  select last_successful_snapshot_id into extra_repo
  from public.projects where id = a_project;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'service_no_snapshot_mutation',
    'passed', n = snap_count_before and extra_repo is not distinct from snap_before,
    'detail', format(
      'expected_snapshots=%s actual_snapshots=%s snapshot_id_unchanged=%s',
      snap_count_before, n, (extra_repo is not distinct from snap_before)
    )
  ));

  perform set_config('request.jwt.claim.sub', user_a::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  perform set_config(
    'request.jwt.claims',
    json_build_object('sub', user_a, 'role', 'authenticated')::text,
    true
  );
  execute 'set local role authenticated';

  begin
    update public.analysis_jobs
      set status = 'failed'
      where trigger_type = 'github_push';
    get diagnostics n = row_count;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_update_github_push_job',
      'passed', n = 0,
      'detail', format('expected=0 actual=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_update_github_push_job',
      'passed', true,
      'detail', format('expected=0-or-error actual=error:%s', sqlerrm)
    ));
  end;

  begin
    delete from public.analysis_jobs where trigger_type = 'github_push';
    get diagnostics n = row_count;
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_delete_github_push_job',
      'passed', n = 0,
      'detail', format('expected=0 actual=%s', n)
    ));
  exception when others then
    results := results || jsonb_build_array(jsonb_build_object(
      'test_name', 'a_cannot_delete_github_push_job',
      'passed', true,
      'detail', format('expected=0-or-error actual=error:%s', sqlerrm)
    ));
  end;

  execute 'reset role';
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);

  select name into b_name from public.projects where id = b_project;
  select count(*) into n from public.projects where id = b_project;
  select count(*) into n2 from public.repositories where id = b_repo;
  results := results || jsonb_build_array(jsonb_build_object(
    'test_name', 'b_data_unchanged_after_a',
    'passed', n = 1 and n2 = 1 and b_name = 'B project',
    'detail', format('expected_projects=1 expected_repos=1 expected_name=B project actual_projects=%s actual_repos=%s actual_name=%s', n, n2, coalesce(b_name, 'null'))
  ));

  insert into isolation_results (test_name, passed, detail)
  select
    e->>'test_name',
    (e->>'passed')::boolean,
    e->>'detail'
  from jsonb_array_elements(results) e;
exception when others then
  execute 'reset role';
  insert into isolation_results (test_name, passed, detail)
  select
    e->>'test_name',
    (e->>'passed')::boolean,
    e->>'detail'
  from jsonb_array_elements(coalesce(results, '[]'::jsonb)) e;
  insert into isolation_results (test_name, passed, detail)
  values (
    'isolation_harness',
    false,
    format('harness_error:%s', sqlerrm)
  );
end;
$isolation$;

select test_name, passed, detail
from isolation_results
order by ord;

rollback;
